name: Hexo Auto Deploy

on:
  push:
    branches:
      - main  # 确保你推送的是 main 分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: sma11black/hexo-action@v1.0.4
        with:
          deploy_key: ${{ secrets.HEXO_DEPLOY_KEY }} # 暂时不用担心这个，如果报错我再教你加密钥
          user_name: bega0
          user_email: 你的GitHub邮箱
