name: Hexo Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # 注意：这里去掉了 cache 选项，避免它寻找不存在的 lock 文件

      - name: Install Hexo and Plugins
        run: |
          npm install -g hexo-cli
          npm install

      - name: Build and Deploy
        run: |
          git config --global user.name "bega0"
          git config --global user.email "你的GitHub邮箱"
          npx hexo clean
          npx hexo g
          # 这一步将生成的静态页面强制推送到 gh-pages 分支
          cd public
          git init
          git add .
          git commit -m "Auto deploy from GitHub Actions"
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
